INSERT INTO "PCR_ROLE_INFO"("ROLEID", "ROLENAME", "ROLESTATE") VALUES ('1', '用户', '启用');
INSERT INTO "PCR_ROLE_INFO"("ROLEID", "ROLENAME", "ROLESTATE") VALUES ('2', '会长', '启用');
INSERT INTO "PCR_ROLE_INFO"("ROLEID", "ROLENAME", "ROLESTATE") VALUES ('3', '管理员', '启用');
