INSERT INTO "PCR_BOOK"("IDKEY", "IDNAME", "PCRID", "PCRNAME") VALUES ('1', 'BOSS状态', '0', '未开始');
INSERT INTO "PCR_BOOK"("IDKEY", "IDNAME", "PCRID", "PCRNAME") VALUES ('2', 'BOSS状态', '1', '开始');
INSERT INTO "PCR_BOOK"("IDKEY", "IDNAME", "PCRID", "PCRNAME") VALUES ('3', 'BOSS状态', '2', '结束');
