INSERT INTO "PCR_ZHANDOU_INFO"("ZHANDOUID", "ZHANDOUTYPE") VALUES ('1', '常规刀');
INSERT INTO "PCR_ZHANDOU_INFO"("ZHANDOUID", "ZHANDOUTYPE") VALUES ('2', '甜心刀');
INSERT INTO "PCR_ZHANDOU_INFO"("ZHANDOUID", "ZHANDOUTYPE") VALUES ('3', '弟弟刀');
INSERT INTO "PCR_ZHANDOU_INFO"("ZHANDOUID", "ZHANDOUTYPE") VALUES ('4', '尾刀');
INSERT INTO "PCR_ZHANDOU_INFO"("ZHANDOUID", "ZHANDOUTYPE") VALUES ('5', '补偿刀');
